[project]
name = "mcp-youtube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.8.0",
    "mcp-use>=1.2.8",
    "bs4>=0.0.2",
    "langchain-groq>=0.3.2",
    "fastembed>=0.6.1",
]
